chore: Kotlin idiomization + `Podfile.lock` lib update
pagopa/io-react-native-http-client pull request #6
Opened 2024-06-06 14:37 UTC by shadowsheep1

## Short description

This PR suggests some Kotlin idiomatic patterns and update the actual lib version in `Podfile.lock`.

2024-06-11 13:45 UTC, Vangaorth requested changes

2024-06-11 13:45 UTC, Vangaorth commented on android/src/main/java/com/pagopa/ioreactnativehttpclient/IoReactNativeHttpClientModule.kt
> +        // TODO: what about handling this scenario?
The main point behind this global try-catch is to mimic iOS behaviour: there, there is no exception raised but a silent failure on bad input parameters.

Here, code may throw, either during URL construction or later in `addCookie` (even if latter does not happen, since it fails for the same reason as former). We do not want the application to crash but it also have to resemble the same behaviour on both platforms, in order to ease the usage from the react-native side.

That is why there is a "global" try-catch with an unhandled catch body

2024-06-11 13:45 UTC, Vangaorth commented on android/src/main/java/com/pagopa/ioreactnativehttpclient/IoReactNativeHttpClientModule.kt
> +        // TODO: what about handling this scenario?
Same as above

2024-06-12 07:22 UTC, shadowsheep1 commented on android/src/main/java/com/pagopa/ioreactnativehttpclient/IoReactNativeHttpClientModule.kt
> +        // TODO: what about handling this scenario?
Okay then. I've removed the `TODO` comment ;)

2024-06-12 07:22 UTC, shadowsheep1 commented on android/src/main/java/com/pagopa/ioreactnativehttpclient/IoReactNativeHttpClientModule.kt
> +        // TODO: what about handling this scenario?
I've removed the TODO comment ;)

2024-06-12 07:25 UTC, Vangaorth approved these changes
LGTM

2024-06-12 07:40 UTC, merged